export interface Country {
  country_name: string;
  emoji: string;
}

export const COUNTRIES: Country[] = [
  { country_name: "Afghanistan", emoji: "🇦🇫" },
  { country_name: "Albania", emoji: "🇦🇱" },
  { country_name: "Algeria", emoji: "🇩🇿" },
  { country_name: "Andorra", emoji: "🇦🇩" },
  { country_name: "Angola", emoji: "🇦🇴" },
  { country_name: "Antigua and Barbuda", emoji: "🇦🇬" },
  { country_name: "Argentina", emoji: "🇦🇷" },
  { country_name: "Armenia", emoji: "🇦🇲" },
  { country_name: "Australia", emoji: "🇦🇺" },
  { country_name: "Austria", emoji: "🇦🇹" },
  { country_name: "Azerbaijan", emoji: "🇦🇿" },
  { country_name: "Bahamas", emoji: "🇧🇸" },
  { country_name: "Bahrain", emoji: "🇧🇭" },
  { country_name: "Bangladesh", emoji: "🇧🇩" },
  { country_name: "Barbados", emoji: "🇧🇧" },
  { country_name: "Belarus", emoji: "🇧🇾" },
  { country_name: "Belgium", emoji: "🇧🇪" },
  { country_name: "Belize", emoji: "🇧🇿" },
  { country_name: "Benin", emoji: "🇧🇯" },
  { country_name: "Bhutan", emoji: "🇧🇹" },
  { country_name: "Bolivia", emoji: "🇧🇴" },
  { country_name: "Bosnia and Herzegovina", emoji: "🇧🇦" },
  { country_name: "Botswana", emoji: "🇧🇼" },
  { country_name: "Brazil", emoji: "🇧🇷" },
  { country_name: "Brunei", emoji: "🇧🇳" },
  { country_name: "Bulgaria", emoji: "🇧🇬" },
  { country_name: "Burkina Faso", emoji: "🇧🇫" },
  { country_name: "Burundi", emoji: "🇧🇮" },
  { country_name: "Cabo Verde", emoji: "🇨🇻" },
  { country_name: "Cambodia", emoji: "🇰🇭" },
  { country_name: "Cameroon", emoji: "🇨🇲" },
  { country_name: "Canada", emoji: "🇨🇦" },
  { country_name: "Central African Republic", emoji: "🇨🇫" },
  { country_name: "Chad", emoji: "🇹🇩" },
  { country_name: "Chile", emoji: "🇨🇱" },
  { country_name: "China", emoji: "🇨🇳" },
  { country_name: "Colombia", emoji: "🇨🇴" },
  { country_name: "Comoros", emoji: "🇰🇲" },
  { country_name: "Congo", emoji: "🇨🇬" },
  { country_name: "Costa Rica", emoji: "🇨🇷" },
  { country_name: "Croatia", emoji: "🇭🇷" },
  { country_name: "Cuba", emoji: "🇨🇺" },
  { country_name: "Cyprus", emoji: "🇨🇾" },
  { country_name: "Czech Republic", emoji: "🇨🇿" },
  { country_name: "Denmark", emoji: "🇩🇰" },
  { country_name: "Djibouti", emoji: "🇩🇯" },
  { country_name: "Dominica", emoji: "🇩🇲" },
  { country_name: "Dominican Republic", emoji: "🇩🇴" },
  { country_name: "Ecuador", emoji: "🇪🇨" },
  { country_name: "Egypt", emoji: "🇪🇬" },
  { country_name: "El Salvador", emoji: "🇸🇻" },
  { country_name: "Equatorial Guinea", emoji: "🇬🇶" },
  { country_name: "Eritrea", emoji: "🇪🇷" },
  { country_name: "Estonia", emoji: "🇪🇪" },
  { country_name: "Eswatini", emoji: "🇸🇿" },
  { country_name: "Ethiopia", emoji: "🇪🇹" },
  { country_name: "Fiji", emoji: "🇫🇯" },
  { country_name: "Finland", emoji: "🇫🇮" },
  { country_name: "France", emoji: "🇫🇷" },
  { country_name: "Gabon", emoji: "🇬🇦" },
  { country_name: "Gambia", emoji: "🇬🇲" },
  { country_name: "Georgia", emoji: "🇬🇪" },
  { country_name: "Germany", emoji: "🇩🇪" },
  { country_name: "Ghana", emoji: "🇬🇭" },
  { country_name: "Greece", emoji: "🇬🇷" },
  { country_name: "Grenada", emoji: "🇬🇩" },
  { country_name: "Guatemala", emoji: "🇬🇹" },
  { country_name: "Guinea", emoji: "🇬🇳" },
  { country_name: "Guinea-Bissau", emoji: "🇬🇼" },
  { country_name: "Guyana", emoji: "🇬🇾" },
  { country_name: "Haiti", emoji: "🇭🇹" },
  { country_name: "Honduras", emoji: "🇭🇳" },
  { country_name: "Hungary", emoji: "🇭🇺" },
  { country_name: "Iceland", emoji: "🇮🇸" },
  { country_name: "India", emoji: "🇮🇳" },
  { country_name: "Indonesia", emoji: "🇮🇩" },
  { country_name: "Iran", emoji: "🇮🇷" },
  { country_name: "Iraq", emoji: "🇮🇶" },
  { country_name: "Ireland", emoji: "🇮🇪" },
  { country_name: "Israel", emoji: "🇮🇱" },
  { country_name: "Italy", emoji: "🇮🇹" },
  { country_name: "Jamaica", emoji: "🇯🇲" },
  { country_name: "Japan", emoji: "🇯🇵" },
  { country_name: "Jordan", emoji: "🇯🇴" },
  { country_name: "Kazakhstan", emoji: "🇰🇿" },
  { country_name: "Kenya", emoji: "🇰🇪" },
  { country_name: "Kiribati", emoji: "🇰🇮" },
  { country_name: "Kuwait", emoji: "🇰🇼" },
  { country_name: "Kyrgyzstan", emoji: "🇰🇬" },
  { country_name: "Laos", emoji: "🇱🇦" },
  { country_name: "Latvia", emoji: "🇱🇻" },
  { country_name: "Lebanon", emoji: "🇱🇧" },
  { country_name: "Lesotho", emoji: "🇱🇸" },
  { country_name: "Liberia", emoji: "🇱🇷" },
  { country_name: "Libya", emoji: "🇱🇾" },
  { country_name: "Liechtenstein", emoji: "🇱🇮" },
  { country_name: "Lithuania", emoji: "🇱🇹" },
  { country_name: "Luxembourg", emoji: "🇱🇺" },
  { country_name: "Madagascar", emoji: "🇲🇬" },
  { country_name: "Malawi", emoji: "🇲🇼" },
  { country_name: "Malaysia", emoji: "🇲🇾" },
  { country_name: "Maldives", emoji: "🇲🇻" },
  { country_name: "Mali", emoji: "🇲🇱" },
  { country_name: "Malta", emoji: "🇲🇹" },
  { country_name: "Marshall Islands", emoji: "🇲🇭" },
  { country_name: "Mauritania", emoji: "🇲🇷" },
  { country_name: "Mauritius", emoji: "🇲🇺" },
  { country_name: "Mexico", emoji: "🇲🇽" },
  { country_name: "Micronesia", emoji: "🇫🇲" },
  { country_name: "Moldova", emoji: "🇲🇩" },
  { country_name: "Monaco", emoji: "🇲🇨" },
  { country_name: "Mongolia", emoji: "🇲🇳" },
  { country_name: "Montenegro", emoji: "🇲🇪" },
  { country_name: "Morocco", emoji: "🇲🇦" },
  { country_name: "Mozambique", emoji: "🇲🇿" },
  { country_name: "Myanmar", emoji: "🇲🇲" },
  { country_name: "Namibia", emoji: "🇳🇦" },
  { country_name: "Nauru", emoji: "🇳🇷" },
  { country_name: "Nepal", emoji: "🇳🇵" },
  { country_name: "Netherlands", emoji: "🇳🇱" },
  { country_name: "New Zealand", emoji: "🇳🇿" },
  { country_name: "Nicaragua", emoji: "🇳🇮" },
  { country_name: "Niger", emoji: "🇳🇪" },
  { country_name: "Nigeria", emoji: "🇳🇬" },
  { country_name: "North Korea", emoji: "🇰🇵" },
  { country_name: "North Macedonia", emoji: "🇲🇰" },
  { country_name: "Norway", emoji: "🇳🇴" },
  { country_name: "Oman", emoji: "🇴🇲" },
  { country_name: "Pakistan", emoji: "🇵🇰" },
  { country_name: "Palau", emoji: "🇵🇼" },
  { country_name: "Palestine", emoji: "🇵🇸" },
  { country_name: "Panama", emoji: "🇵🇦" },
  { country_name: "Papua New Guinea", emoji: "🇵🇬" },
  { country_name: "Paraguay", emoji: "🇵🇾" },
  { country_name: "Peru", emoji: "🇵🇪" },
  { country_name: "Philippines", emoji: "🇵🇭" },
  { country_name: "Poland", emoji: "🇵🇱" },
  { country_name: "Portugal", emoji: "🇵🇹" },
  { country_name: "Qatar", emoji: "🇶🇦" },
  { country_name: "Romania", emoji: "🇷🇴" },
  { country_name: "Russia", emoji: "🇺🇦" },
  { country_name: "Rwanda", emoji: "🇷🇼" },
  { country_name: "Saint Kitts and Nevis", emoji: "🇰🇳" },
  { country_name: "Saint Lucia", emoji: "🇱🇨" },
  { country_name: "Saint Vincent and the Grenadines", emoji: "🇻🇨" },
  { country_name: "Samoa", emoji: "🇼🇸" },
  { country_name: "San Marino", emoji: "🇸🇲" },
  { country_name: "Saudi Arabia", emoji: "🇸🇦" },
  { country_name: "Senegal", emoji: "🇸🇳" },
  { country_name: "Serbia", emoji: "🇷🇸" },
  { country_name: "Seychelles", emoji: "🇸🇨" },
  { country_name: "Sierra Leone", emoji: "🇸🇱" },
  { country_name: "Singapore", emoji: "🇸🇬" },
  { country_name: "Slovakia", emoji: "🇸🇰" },
  { country_name: "Slovenia", emoji: "🇸🇮" },
  { country_name: "Solomon Islands", emoji: "🇸🇧" },
  { country_name: "Somalia", emoji: "🇸🇴" },
  { country_name: "South Africa", emoji: "🇿🇦" },
  { country_name: "South Korea", emoji: "🇰🇷" },
  { country_name: "South Sudan", emoji: "🇸🇸" },
  { country_name: "Spain", emoji: "🇪🇸" },
  { country_name: "Sri Lanka", emoji: "🇱🇰" },
  { country_name: "Sudan", emoji: "🇸🇩" },
  { country_name: "Suriname", emoji: "🇸🇷" },
  { country_name: "Sweden", emoji: "🇸🇪" },
  { country_name: "Switzerland", emoji: "🇨🇭" },
  { country_name: "Syria", emoji: "🇸🇾" },
  { country_name: "Taiwan", emoji: "🇹🇼" },
  { country_name: "Tajikistan", emoji: "🇹🇯" },
  { country_name: "Tanzania", emoji: "🇹🇿" },
  { country_name: "Thailand", emoji: "🇹🇭" },
  { country_name: "Timor-Leste", emoji: "🇹🇱" },
  { country_name: "Togo", emoji: "🇹🇬" },
  { country_name: "Tonga", emoji: "🇹🇴" },
  { country_name: "Trinidad and Tobago", emoji: "🇹🇹" },
  { country_name: "Tunisia", emoji: "🇹🇳" },
  { country_name: "Turkey", emoji: "🇹🇷" },
  { country_name: "Turkmenistan", emoji: "🇹🇲" },
  { country_name: "Tuvalu", emoji: "🇹🇻" },
  { country_name: "Uganda", emoji: "🇺🇬" },
  { country_name: "Ukraine", emoji: "🇺🇦" },
  { country_name: "United Arab Emirates", emoji: "🇦🇪" },
  { country_name: "United Kingdom", emoji: "🇬🇧" },
  { country_name: "United States", emoji: "🇺🇸" },
  { country_name: "Uruguay", emoji: "🇺🇾" },
  { country_name: "Uzbekistan", emoji: "🇺🇿" },
  { country_name: "Vanuatu", emoji: "🇻🇺" },
  { country_name: "Venezuela", emoji: "🇻🇪" },
  { country_name: "Vietnam", emoji: "🇻🇳" },
  { country_name: "Yemen", emoji: "🇾🇪" },
  { country_name: "Zambia", emoji: "🇿🇲" },
  { country_name: "Zimbabwe", emoji: "🇿🇼" },
];
