"use client";

import { startTransition, useState } from "react";
import { useRouter } from "next/navigation";
import { RotateCcw, Loader2, TriangleAlert } from "lucide-react";
import { toast } from "sonner";
import type { PlatformMetadata } from "@/lib/metadata/types";
import { Button } from "@/components/ui/button";
import { Card, CardAction, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tooltip } from "@/components/ui/tooltip";

interface MetadataSectionProps {
  postId: string;
  platformLabel: string;
  metadata: PlatformMetadata;
}

export function MetadataSection({ postId, platformLabel, metadata }: MetadataSectionProps) {
  const router = useRouter();
  const [regenerating, setRegenerating] = useState(false);
  const regenerateHint = "It will wipe and regenerate metadata of the post.";

  async function handleRegenerate() {
    setRegenerating(true);
    try {
      const res = await fetch(`/api/posts/${postId}/metadata`, { method: "POST" });
      if (!res.ok) {
        const err = await res.json();
        throw new Error(err.error ?? "Failed to queue metadata regeneration");
      }
      toast.success("Metadata regeneration started.");
      startTransition(() => router.refresh());
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to queue metadata regeneration");
    } finally {
      setRegenerating(false);
    }
  }

  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-sm font-medium">
          {platformLabel} Metadata
          <span className="text-xs font-normal text-muted-foreground ml-2">generated by AI</span>
        </CardTitle>
        <CardAction>
          <Tooltip
            content={
              <span className="flex items-start gap-2">
                <TriangleAlert className="mt-0.5 h-3.5 w-3.5 shrink-0 text-golden-earth-600 dark:text-golden-earth-400" />
                <span>{regenerateHint}</span>
              </span>
            }
          >
            <Button
              type="button"
              variant="ghost"
              size="icon-sm"
              onClick={handleRegenerate}
              disabled={regenerating}
              aria-label={regenerateHint}
            >
              {regenerating ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <RotateCcw className="h-3.5 w-3.5" />}
            </Button>
          </Tooltip>
        </CardAction>
      </CardHeader>
      <CardContent className="space-y-3 text-sm">
        <MetadataDisplay metadata={metadata} />
      </CardContent>
    </Card>
  );
}

function MetadataDisplay({ metadata }: { metadata: PlatformMetadata }) {
  if (metadata.platform === "INSTAGRAM" || metadata.platform === "TIKTOK") {
    return (
      <>
        <div>
          <p className="text-xs text-muted-foreground mb-1">Caption</p>
          <p className="whitespace-pre-wrap text-sm">{metadata.caption}</p>
        </div>
        <div>
          <p className="text-xs text-muted-foreground mb-1">Hashtags</p>
          <div className="flex flex-wrap gap-1">
            {metadata.hashtags.map((h) => (
              <span key={h} className="text-xs bg-muted px-1.5 py-0.5 rounded">#{h}</span>
            ))}
          </div>
        </div>
      </>
    );
  }

  return (
    <>
      <div>
        <p className="text-xs text-muted-foreground mb-1">Title</p>
        <p className="font-medium">{metadata.title}</p>
      </div>
      <div>
        <p className="text-xs text-muted-foreground mb-1">Description</p>
        <p className="whitespace-pre-wrap">{metadata.description}</p>
      </div>
      <div>
        <p className="text-xs text-muted-foreground mb-1">Tags</p>
        <div className="flex flex-wrap gap-1">
          {metadata.tags.map((t) => (
            <span key={t} className="text-xs bg-muted px-1.5 py-0.5 rounded">{t}</span>
          ))}
        </div>
      </div>
    </>
  );
}
