services:
  app:
    build:
      target: prod
    command: sh -c "npm run start 2>&1 | tee /logs/dev.log"
    volumes:
      - ./storage:/app/storage
      - .:/logs

  worker:
    build:
      target: prod
    command: sh -c "npm run worker:start 2>&1 | tee /logs/worker.log"
    volumes:
      - ./storage:/app/storage
      - .:/logs

volumes:
  app_node_modules: ~
  worker_node_modules: ~
