import { prisma } from "@/lib/db";
import { notFound } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft } from "lucide-react";
import { PLATFORM_LABELS, STATUS_CONFIG, formatDistanceToNow } from "@/lib/utils";
import type { PlatformMetadata } from "@/lib/metadata/types";
import { VideoSection } from "@/components/posts/VideoSection";
import { PostEditPanel } from "@/components/posts/PostEditPanel";
import { listVoices } from "@/lib/heygen/client";
import { isPostEditable } from "@/lib/posts";
import { getLLMModelInfo } from "@/lib/llm-models/registry";

export default async function PostDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const [post, voices] = await Promise.all([
    prisma.post.findUnique({ where: { id }, include: { avatar: true } }),
    listVoices().catch(() => []),
  ]);
  if (!post) notFound();

  const voice = voices.find((v) => v.voice_id === post.avatar.voiceId);
  const llmModel = getLLMModelInfo(post.llmModelId);

  const metadata: PlatformMetadata | null = post.metadata ? JSON.parse(post.metadata) : null;
  const statusCfg = STATUS_CONFIG[post.status] ?? STATUS_CONFIG.DRAFT;
  const canEditPost = isPostEditable(post);

  return (
    <div className="px-6 py-8 sm:px-10 space-y-6">
      <div className="flex items-center gap-3">
        <Link href="/posts" className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground">
          <ArrowLeft className="h-4 w-4 mr-1" />Back
        </Link>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="space-y-4">
          {/* Video / generation area */}
          <VideoSection
            post={{
              id: post.id,
              status: post.status,
              videoPath: post.videoPath,
              errorMessage: post.errorMessage,
              generationStartedAt: post.generationStartedAt?.toISOString() ?? null,
            }}
          />

          {/* Avatar info */}
          <Card>
            <CardContent className="pt-4 flex items-center gap-3">
              <div className="h-12 w-12 relative rounded-md overflow-hidden bg-muted shrink-0">
                <Image
                  src={`/api/avatars/${post.avatar.id}/image`}
                  alt={post.avatar.name}
                  fill
                  className="object-cover"
                  unoptimized
                />
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-medium">{post.avatar.name}</p>
                <Link href={`/avatars/${post.avatar.id}`} className="text-xs text-muted-foreground hover:underline">View avatar</Link>
              </div>
              {voice && (
                <div className="text-right shrink-0">
                  <p className="text-xs text-muted-foreground">Voice</p>
                  <p className="text-sm font-medium">{voice.name}</p>
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        <div className="md:col-span-2 space-y-4">
          <PostEditPanel
            editable={canEditPost}
            post={{
              id: post.id,
              title: post.title,
              platformLabel: PLATFORM_LABELS[post.platform],
              statusLabel: statusCfg.label,
              script: post.script,
              llmModelId: post.llmModelId,
              llmModelName: llmModel?.name ?? post.llmModelId,
              avatarName: post.avatar.name,
              voiceName: voice?.name ?? null,
              createdAtLabel: formatDistanceToNow(post.createdAt),
              status: post.status,
              downloadUrl: post.status === "COMPLETED" ? `/api/posts/${post.id}/download` : null,
            }}
          />

          {metadata && (
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium">
                  {PLATFORM_LABELS[post.platform]} Metadata
                  <span className="text-xs font-normal text-muted-foreground ml-2">generated by AI</span>
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3 text-sm">
                <MetadataDisplay metadata={metadata} />
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
}

function MetadataDisplay({ metadata }: { metadata: PlatformMetadata }) {
  if (metadata.platform === "INSTAGRAM" || metadata.platform === "TIKTOK") {
    return (
      <>
        <div>
          <p className="text-xs text-muted-foreground mb-1">Caption</p>
          <p className="whitespace-pre-wrap text-sm">{metadata.caption}</p>
        </div>
        <div>
          <p className="text-xs text-muted-foreground mb-1">Hashtags</p>
          <div className="flex flex-wrap gap-1">
            {metadata.hashtags.map((h) => (
              <span key={h} className="text-xs bg-muted px-1.5 py-0.5 rounded">#{h}</span>
            ))}
          </div>
        </div>
      </>
    );
  }
  return (
    <>
      <div>
        <p className="text-xs text-muted-foreground mb-1">Title</p>
        <p className="font-medium">{metadata.title}</p>
      </div>
      <div>
        <p className="text-xs text-muted-foreground mb-1">Description</p>
        <p className="whitespace-pre-wrap">{metadata.description}</p>
      </div>
      <div>
        <p className="text-xs text-muted-foreground mb-1">Tags</p>
        <div className="flex flex-wrap gap-1">
          {metadata.tags.map((t) => (
            <span key={t} className="text-xs bg-muted px-1.5 py-0.5 rounded">{t}</span>
          ))}
        </div>
      </div>
    </>
  );
}
