import { prisma } from "@/lib/db";
import { notFound } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft, Download } from "lucide-react";
import { PLATFORM_LABELS, STATUS_CONFIG, formatDistanceToNow } from "@/lib/utils";
import type { PlatformMetadata } from "@/lib/metadata/types";
import { VideoSection } from "@/components/posts/VideoSection";

export default async function PostDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const post = await prisma.post.findUnique({ where: { id }, include: { avatar: true } });
  if (!post) notFound();

  const metadata: PlatformMetadata | null = post.metadata ? JSON.parse(post.metadata) : null;
  const statusCfg = STATUS_CONFIG[post.status] ?? STATUS_CONFIG.DRAFT;

  return (
    <div className="p-8 max-w-4xl mx-auto space-y-6">
      <div className="flex items-center gap-3">
        <Link href="/posts" className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground">
          <ArrowLeft className="h-4 w-4 mr-1" />Back
        </Link>
      </div>

      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-semibold">{post.title}</h1>
          <div className="flex items-center gap-2 mt-2">
            <Badge variant="outline">{PLATFORM_LABELS[post.platform]}</Badge>
            <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${statusCfg.className}`}>
              {statusCfg.label}
            </span>
            <span className="text-xs text-muted-foreground">{formatDistanceToNow(post.createdAt)}</span>
          </div>
        </div>
        {post.status === "COMPLETED" && (
          <a href={`/api/posts/${post.id}/download`} download>
            <Button>
              <Download className="h-4 w-4 mr-1.5" />Download Package
            </Button>
          </a>
        )}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="space-y-4">
          {/* Video / generation area */}
          <VideoSection post={{ id: post.id, status: post.status, videoPath: post.videoPath, errorMessage: post.errorMessage }} />

          {/* Avatar info */}
          <Card>
            <CardContent className="pt-4 flex items-center gap-3">
              <div className="h-12 w-12 relative rounded-md overflow-hidden bg-muted shrink-0">
                <Image
                  src={`/api/avatars/${post.avatar.id}/image`}
                  alt={post.avatar.name}
                  fill
                  className="object-cover"
                  unoptimized
                />
              </div>
              <div>
                <p className="text-sm font-medium">{post.avatar.name}</p>
                <Link href={`/avatars/${post.avatar.id}`} className="text-xs text-muted-foreground hover:underline">View avatar</Link>
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="space-y-4">
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Script</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm whitespace-pre-wrap">{post.script}</p>
            </CardContent>
          </Card>

          {metadata && (
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium">
                  {PLATFORM_LABELS[post.platform]} Metadata
                  <span className="text-xs font-normal text-muted-foreground ml-2">generated by AI</span>
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3 text-sm">
                <MetadataDisplay metadata={metadata} />
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
}

function MetadataDisplay({ metadata }: { metadata: PlatformMetadata }) {
  if (metadata.platform === "INSTAGRAM" || metadata.platform === "TIKTOK") {
    return (
      <>
        <div>
          <p className="text-xs text-muted-foreground mb-1">Caption</p>
          <p className="whitespace-pre-wrap text-sm">{metadata.caption}</p>
        </div>
        <div>
          <p className="text-xs text-muted-foreground mb-1">Hashtags</p>
          <div className="flex flex-wrap gap-1">
            {metadata.hashtags.map((h) => (
              <span key={h} className="text-xs bg-muted px-1.5 py-0.5 rounded">#{h}</span>
            ))}
          </div>
        </div>
      </>
    );
  }
  return (
    <>
      <div>
        <p className="text-xs text-muted-foreground mb-1">Title</p>
        <p className="font-medium">{metadata.title}</p>
      </div>
      <div>
        <p className="text-xs text-muted-foreground mb-1">Description</p>
        <p className="whitespace-pre-wrap">{metadata.description}</p>
      </div>
      <div>
        <p className="text-xs text-muted-foreground mb-1">Tags</p>
        <div className="flex flex-wrap gap-1">
          {metadata.tags.map((t) => (
            <span key={t} className="text-xs bg-muted px-1.5 py-0.5 rounded">{t}</span>
          ))}
        </div>
      </div>
    </>
  );
}
